all:
	pdflatex main
	# bibtex main
	# pdflatex main
	# pdflatex main

.PHONY: clean
clean:
	rm -f main.out
	rm -f main.aux
	rm -f main.bbl
	rm -f main.blg
	rm -f main.fls
	rm -f main.log
	rm -f main.out
	rm -f main.toc
	rm -f main.dvi
	rm -f main.nav
	rm -f main.snm
	rm -f main.vrb
	rm -f main.synctex.gz
	rm -f main.fdb_latexmk
