all:
	pdflatex praca
	bibtex praca
	pdflatex praca
	pdflatex praca

.PHONY: clean
clean:
	rm -f praca.out
	rm -f praca.aux
	rm -f praca.bbl
	rm -f praca.blg
	rm -f praca.fdb_latexmk
	rm -f praca.fls
	rm -f praca.log
	rm -f praca.loa
	rm -f praca.lot
	rm -f praca.lof
	rm -f praca.out
	rm -f praca.toc
	rm -f praca.synctex.gz
